/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.SanPham_BUS;
import connectDB.ConnectDB;
import entities.SanPham;
import entities.TacGia;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ChiTietSanPham extends javax.swing.JPanel {

    /**
     * Creates new form ChiTietSanPham
     */
    public ChiTietSanPham() {
        initComponents();
    }
    
    public ChiTietSanPham(SanPham x) {
        initComponents();
        ConnectDB.getInstance().connect();
        SanPham_BUS sanPham_BUS = new SanPham_BUS();
        
   
   

        this.jLabel_TenSanPham.setText(x.getTenSanPham());
        this.jLabel_TacGia.setText(sanPham_BUS.getNameTacGiaByID(x.getTacGia().getTacGiaID()));
        this.jLabel_DanhMuc.setText(sanPham_BUS.getNameDanhMucByID(x.getDanhMuc().getDanhMucID()));
        this.jLabel_NhaXuatBan.setText(sanPham_BUS.getNameNhaXuatBanByID(x.getNhaXuatBan().getNhaXuatBanID()));
        this.jLabel_SoLuong.setText(x.getSoLuongTon() + "");
        
//        if (getClass().getResource(x.getImgPath().toString()) == null){
//            jLabel_Img.setText("No image");
//            return;
//        }

        ImageIcon imageIcon = new ImageIcon("src/" + x.getImgPath()); // load the image to a imageIcon

        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(150, 220,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg); 
        this.jLabel_Img.setIcon(imageIcon);
        

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Component_SanPham = new javax.swing.JPanel();
        jPanel_Box_Left = new javax.swing.JPanel();
        jLabel_Img = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 0));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(5, 10), new java.awt.Dimension(0, 0));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(5, 20), new java.awt.Dimension(0, 0));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 5), new java.awt.Dimension(0, 0));
        jPanel_Info_SanPham1 = new javax.swing.JPanel();
        jPanel159 = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel_TenSanPham1 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        jLabel_TenSanPham = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel160 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel_TacGia = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel161 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jLabel_NhaXuatBan = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel162 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel_DanhMuc = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel163 = new javax.swing.JPanel();
        jLabel130 = new javax.swing.JLabel();
        jLabel_SoLuong = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel164 = new javax.swing.JPanel();
        jButton_Sua = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 30), new java.awt.Dimension(10, 10));
        jButton_NgungBan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Component_SanPham.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Component_SanPham.setMinimumSize(new java.awt.Dimension(430, 300));
        jPanel_Component_SanPham.setLayout(new javax.swing.BoxLayout(jPanel_Component_SanPham, javax.swing.BoxLayout.LINE_AXIS));

        jPanel_Box_Left.setPreferredSize(new java.awt.Dimension(170, 254));
        jPanel_Box_Left.setLayout(new java.awt.BorderLayout());

        jLabel_Img.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Img.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Img.setPreferredSize(new java.awt.Dimension(150, 300));
        jPanel_Box_Left.add(jLabel_Img, java.awt.BorderLayout.CENTER);
        jLabel_Img.getAccessibleContext().setAccessibleName("");

        jPanel_Box_Left.add(filler11, java.awt.BorderLayout.LINE_END);
        jPanel_Box_Left.add(filler12, java.awt.BorderLayout.PAGE_START);
        jPanel_Box_Left.add(filler13, java.awt.BorderLayout.PAGE_END);
        jPanel_Box_Left.add(filler14, java.awt.BorderLayout.LINE_START);

        jPanel_Component_SanPham.add(jPanel_Box_Left);

        jPanel_Info_SanPham1.setLayout(new java.awt.BorderLayout());

        jPanel159.setLayout(new javax.swing.BoxLayout(jPanel159, javax.swing.BoxLayout.Y_AXIS));
        jPanel159.add(filler8);
        jPanel159.add(filler10);

        jPanel_TenSanPham1.setAlignmentX(0.0F);
        jPanel_TenSanPham1.setLayout(new javax.swing.BoxLayout(jPanel_TenSanPham1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel132.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel132.setText("Tên sản phẩm: ");
        jPanel_TenSanPham1.add(jLabel132);

        jLabel_TenSanPham.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_TenSanPham.setText("Field_TenSanPham");
        jPanel_TenSanPham1.add(jLabel_TenSanPham);

        jPanel159.add(jPanel_TenSanPham1);
        jPanel159.add(filler1);

        jPanel160.setAlignmentX(0.0F);
        jPanel160.setLayout(new javax.swing.BoxLayout(jPanel160, javax.swing.BoxLayout.LINE_AXIS));

        jLabel124.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel124.setText("Tác giả: ");
        jPanel160.add(jLabel124);

        jLabel_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_TacGia.setText("Field_TacGia");
        jPanel160.add(jLabel_TacGia);

        jPanel159.add(jPanel160);
        jPanel159.add(filler2);

        jPanel161.setAlignmentX(0.0F);
        jPanel161.setLayout(new javax.swing.BoxLayout(jPanel161, javax.swing.BoxLayout.LINE_AXIS));

        jLabel126.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel126.setText("Nhà xuất bản: ");
        jPanel161.add(jLabel126);

        jLabel_NhaXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_NhaXuatBan.setText("Field_NhaXuatBan");
        jPanel161.add(jLabel_NhaXuatBan);

        jPanel159.add(jPanel161);
        jPanel159.add(filler3);

        jPanel162.setAlignmentX(0.0F);
        jPanel162.setLayout(new javax.swing.BoxLayout(jPanel162, javax.swing.BoxLayout.LINE_AXIS));

        jLabel128.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel128.setText("Danh mục: ");
        jPanel162.add(jLabel128);

        jLabel_DanhMuc.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_DanhMuc.setText("Field_DanhMuc");
        jPanel162.add(jLabel_DanhMuc);

        jPanel159.add(jPanel162);
        jPanel159.add(filler4);

        jPanel163.setAlignmentX(0.0F);
        jPanel163.setLayout(new javax.swing.BoxLayout(jPanel163, javax.swing.BoxLayout.LINE_AXIS));

        jLabel130.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel130.setText("Số lượng: ");
        jPanel163.add(jLabel130);

        jLabel_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_SoLuong.setText("Field_SoLuong");
        jPanel163.add(jLabel_SoLuong);

        jPanel159.add(jPanel163);
        jPanel159.add(filler5);
        jPanel159.add(filler6);
        jPanel159.add(filler7);

        jPanel164.setAlignmentX(0.0F);
        jPanel164.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel164.setLayout(new javax.swing.BoxLayout(jPanel164, javax.swing.BoxLayout.LINE_AXIS));

        jButton_Sua.setBackground(new java.awt.Color(85, 182, 83));
        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_Sua.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Sua.setText("Sửa");
        jButton_Sua.setAutoscrolls(true);
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel164.add(jButton_Sua);
        jPanel164.add(filler9);

        jButton_NgungBan.setBackground(new java.awt.Color(219, 79, 78));
        jButton_NgungBan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_NgungBan.setForeground(new java.awt.Color(255, 255, 255));
        jButton_NgungBan.setText("Ngừng bán");
        jButton_NgungBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgungKDActionPerformed(evt);
            }
        });
        jPanel164.add(jButton_NgungBan);

        jPanel159.add(jPanel164);

        jPanel_Info_SanPham1.add(jPanel159, java.awt.BorderLayout.CENTER);

        jPanel_Component_SanPham.add(jPanel_Info_SanPham1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Component_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Component_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnNgungKDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgungKDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNgungKDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton_NgungBan;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel_DanhMuc;
    private javax.swing.JLabel jLabel_Img;
    private javax.swing.JLabel jLabel_NhaXuatBan;
    private javax.swing.JLabel jLabel_SoLuong;
    private javax.swing.JLabel jLabel_TacGia;
    private javax.swing.JLabel jLabel_TenSanPham;
    private javax.swing.JPanel jPanel159;
    private javax.swing.JPanel jPanel160;
    private javax.swing.JPanel jPanel161;
    private javax.swing.JPanel jPanel162;
    private javax.swing.JPanel jPanel163;
    private javax.swing.JPanel jPanel164;
    private javax.swing.JPanel jPanel_Box_Left;
    private javax.swing.JPanel jPanel_Component_SanPham;
    private javax.swing.JPanel jPanel_Info_SanPham1;
    private javax.swing.JPanel jPanel_TenSanPham1;
    // End of variables declaration//GEN-END:variables
}
