/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenThanhLuan
 */
public class Form_DanhSachVoucher extends javax.swing.JPanel {

    /**
     * Creates new form Form_DanhSachVoucher
     */
    public Form_DanhSachVoucher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVoucher = new javax.swing.JPanel();
        titleSelectKhuyenMai = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        comboboxApDung = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        TimMaSanPham = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        tableSelectKhuyenMai = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChonSP = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnlVoucher.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 1, 1));
        pnlVoucher.setPreferredSize(new java.awt.Dimension(602, 310));
        pnlVoucher.setLayout(new java.awt.BorderLayout());

        titleSelectKhuyenMai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        titleSelectKhuyenMai.setPreferredSize(new java.awt.Dimension(602, 72));
        titleSelectKhuyenMai.setLayout(new java.awt.GridLayout(2, 2, 0, 8));

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setText("Áp dụng theo thương hiệu: ");
        jPanel17.add(jLabel10);
        jPanel17.add(filler3);

        comboboxApDung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        comboboxApDung.setFocusable(false);
        jPanel17.add(comboboxApDung);

        titleSelectKhuyenMai.add(jPanel17);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        titleSelectKhuyenMai.add(jPanel16);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));
        titleSelectKhuyenMai.add(jPanel14);

        jPanel12.setLayout(new java.awt.BorderLayout(10, 0));
        jPanel12.add(TimMaSanPham, java.awt.BorderLayout.CENTER);

        btnTimKiem.setBackground(new java.awt.Color(15, 145, 239));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/icon-addKM.png"))); // NOI18N
        btnTimKiem.setPreferredSize(new java.awt.Dimension(80, 23));
        jPanel12.add(btnTimKiem, java.awt.BorderLayout.EAST);

        titleSelectKhuyenMai.add(jPanel12);

        pnlVoucher.add(titleSelectKhuyenMai, java.awt.BorderLayout.PAGE_START);

        tableSelectKhuyenMai.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        tableSelectKhuyenMai.setPreferredSize(new java.awt.Dimension(870, 200));
        tableSelectKhuyenMai.setLayout(new java.awt.BorderLayout());

        tableChonSP.setModel(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Chọn", "Mã sản phẩm", "Tên sản phẩm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableChonSP);

        tableSelectKhuyenMai.add(jScrollPane2, java.awt.BorderLayout.PAGE_START);

        pnlVoucher.add(tableSelectKhuyenMai, java.awt.BorderLayout.CENTER);

        add(pnlVoucher, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TimMaSanPham;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> comboboxApDung;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlVoucher;
    private javax.swing.JTable tableChonSP;
    private javax.swing.JPanel tableSelectKhuyenMai;
    private javax.swing.JPanel titleSelectKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
