/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.table.DefaultTableModel;

import entities.KhuyenMai;

/**
 *
 * @author NguyenThanhLuan
 */
public class Form_DanhSachVoucher extends javax.swing.JFrame {
	private ArrayList<KhuyenMai> listVoucher;
	private DefaultTableModel tableModelVoucher;
	private SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
	private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
	private DecimalFormat fmt = new DecimalFormat("###,###");
    /**
     * Creates new form Form_DanhSachVoucher
     */
    public Form_DanhSachVoucher(ArrayList<KhuyenMai> listVoucher) {
        initComponents();
        this.listVoucher = listVoucher;
    }
    
	private String today() {
		Date ngayHienTai = new Date();
		return sdf.format(ngayHienTai);
	}
    
    private void loadVoucher() {
    	for(KhuyenMai km : listVoucher) {
    		tableModelVoucher.addRow(new Object[] {km.getCodeKhuyenMai(),today(), km.getNgayKhuyenMai(), km.getNgayHetHanKM(), km.getLoaiKhuyenMai(), km.getDonHangTu(), km.getGiaTri()});
    	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ALL = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVoucher = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1120, 600));
        setMinimumSize(new java.awt.Dimension(1120, 600));
        setPreferredSize(new java.awt.Dimension(1120, 600));

        ALL.setLayout(new java.awt.BorderLayout());
        ALL.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 145, 239));
        jLabel1.setText("Danh sách voucher");
        jPanel5.add(jLabel1);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        tableVoucher.setModel(tableModelVoucher = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã giảm giá", "Ngày tạo", "Ngày kích hoạt", "Ngày hết hạn ", "Hình thức giảm","Đon hàng từ" ,"Mức giảm giá", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableVoucher);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        ALL.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(285, 58));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 14));

        jButton1.setText("Import");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel2.add(jButton1);
        jPanel2.add(filler2);

        jButton2.setText("Trở về");
        jButton2.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel2.add(jButton2);
        jPanel2.add(filler1);

        ALL.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/icon-voucher.png"))); // NOI18N
        jPanel3.add(jLabel3);

        ALL.add(jPanel3, java.awt.BorderLayout.LINE_START);

        getContentPane().add(ALL, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALL;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVoucher;
    // End of variables declaration//GEN-END:variables
}
