/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import bus.ChiTietKhuyenMai_BUS;
import entities.ChiTietKhuyenMai;
import entities.KhuyenMai;

/**
 *
 * @author NguyenThanhLuan
 */
public class GUI_XemChiTietKhuyeMai extends javax.swing.JFrame {
	private DefaultTableModel tableModel;
	private ArrayList<ChiTietKhuyenMai> danhSachCT;
	private ChiTietKhuyenMai_BUS busChiTietKhuyenMai_BUS;
    /**
     * Creates new form GUI_XemChiTietKhuyeMai
     */
    public GUI_XemChiTietKhuyeMai() {
        initComponents();
        busChiTietKhuyenMai_BUS = new ChiTietKhuyenMai_BUS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChiTietSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        jPanel1.setLayout(new java.awt.BorderLayout());

        tableChiTietSanPham.setModel(tableModel = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Mã khuyến mãi", "Tên sản phẩm", "Tên khuyến mãi", "Ngày tạo"
            }
        ));
        jScrollPane1.setViewportView(tableChiTietSanPham);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void loadDuLieu() {
    	tableChiTietSanPham.removeAll();
    	tableChiTietSanPham.setRowSelectionAllowed(false);
    	tableModel.setRowCount(0);
    	danhSachCT = new ArrayList<>();
    	danhSachCT = busChiTietKhuyenMai_BUS.getAllChiTietKhuyenMai();
    	int stt = 1;
    	for(ChiTietKhuyenMai ctkm : danhSachCT) {
    		tableModel.addRow(new Object[] {stt++,ctkm.getSanPham().getSanPhamID(), ctkm.getKhuyenMai().getCodeKhuyenMai(), ctkm.getKhuyenMai().getCodeKhuyenMai(),ctkm.getKhuyenMai().getCodeKhuyenMai(), ctkm.getNgayTao()});
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableChiTietSanPham;
    // End of variables declaration//GEN-END:variables
}
