package gui;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.Border;
import utilities.ColorProcessing;

/**
 *
 * @author duong
 */
public class GUI_MainMenu extends javax.swing.JFrame {

    private int sizeIconBar = 30;
    /**
     * Creates new form MainMenu
     */
    public GUI_MainMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        utilities.ImageProcessing.scaleImageFitToLabel(lblLogo, new ImageIcon(this.getClass().getResource("/img/logo/whimsibooks-logo.png")));
        cboUser.setFocusable(false);
        cboUser.enableInputMethods(false);
        cboUser.setPopupVisible(false);
        jPannelSplit.setBorder(null);
        //Border pannelBorder =  BorderFactory.createMatteBorder(0, 0, 0, 1, ColorProcessing.rgbColor(15, 102, 165));
        //pannelLeft.setBorder(pannelBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jFrame2 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboUser = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPannelSplit = new javax.swing.JSplitPane();
        panelRight = new javax.swing.JPanel();
        pannelLeft = new javax.swing.JPanel();
        tabBanHang = new javax.swing.JButton();
        tabSanPham = new javax.swing.JButton();
        tabKhuyenMai = new javax.swing.JButton();
        tabThongKe = new javax.swing.JButton();
        tabNhanVien = new javax.swing.JButton();
        tabKhachHang = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        tabNhaCungCap1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        cboUser.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cboUser.setMaximumRowCount(2);
        cboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chào, Dương Thái Bảo", "Đăng xuất" }));
        cboUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 653, Short.MAX_VALUE)
                .addComponent(cboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPannelSplit.setDividerSize(4);
        jPannelSplit.setForeground(new java.awt.Color(255, 255, 255));
        jPannelSplit.setToolTipText("");
        jPannelSplit.setFocusable(false);

        panelRight.setLayout(new java.awt.BorderLayout());
        jPannelSplit.setRightComponent(panelRight);

        java.awt.GridBagLayout jPanel5Layout = new java.awt.GridBagLayout();
        jPanel5Layout.columnWidths = new int[] {0, 23, 0, 23, 0};
        jPanel5Layout.rowHeights = new int[] {0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0};
        pannelLeft.setLayout(jPanel5Layout);

        tabBanHang.setBackground(new java.awt.Color(15, 145, 239));
        tabBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabBanHang.setForeground(new java.awt.Color(255, 255, 255));
        tabBanHang.setIcon(
            utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/ico-banhang.png"))
                , sizeIconBar, sizeIconBar)
        );
        tabBanHang.setText("Bán hàng");
        tabBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabBanHang.setFocusable(false);
        tabBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tabBanHang.setIconTextGap(25);
        tabBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabBanHangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        pannelLeft.add(tabBanHang, gridBagConstraints);

        tabSanPham.setBackground(Color.white);
        tabSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabSanPham.setForeground(new java.awt.Color(15, 102, 165));
        tabSanPham.setIcon(
            utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/ico-sanpham.png"))
                , sizeIconBar, sizeIconBar)
        );
        tabSanPham.setText("Sản phẩm");
        tabSanPham.setToolTipText("");
        tabSanPham.setFocusable(false);
        tabSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tabSanPham.setIconTextGap(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 0.1;
        pannelLeft.add(tabSanPham, gridBagConstraints);

        tabKhuyenMai.setBackground(Color.white);
        tabKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabKhuyenMai.setForeground(new java.awt.Color(15, 102, 165));
        tabKhuyenMai.setIcon(
            utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(
                getClass().getResource("/img/icon/ico-khuyenmai.png"))
            , sizeIconBar, sizeIconBar)
    );
    tabKhuyenMai.setText("Khuyến mãi");
    tabKhuyenMai.setFocusable(false);
    tabKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
    tabKhuyenMai.setIconTextGap(25);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 39;
    gridBagConstraints.ipady = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
    gridBagConstraints.weightx = 0.1;
    pannelLeft.add(tabKhuyenMai, gridBagConstraints);

    tabThongKe.setBackground(Color.white);
    tabThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    tabThongKe.setForeground(new java.awt.Color(15, 102, 165));
    tabThongKe.setIcon(utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/icon/ico-thongke.png"))
    , sizeIconBar, sizeIconBar)
    );
    tabThongKe.setText("Thống kê");
    tabThongKe.setFocusable(false);
    tabThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
    tabThongKe.setIconTextGap(25);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 39;
    gridBagConstraints.ipady = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
    gridBagConstraints.weightx = 0.1;
    pannelLeft.add(tabThongKe, gridBagConstraints);

    tabNhanVien.setBackground(Color.white);
    tabNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    tabNhanVien.setForeground(new java.awt.Color(15, 102, 165));
    tabNhanVien.setIcon(utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/icon/ico-nhanvien.png"))  
    , sizeIconBar, sizeIconBar));
    tabNhanVien.setText("Nhân viên");
    tabNhanVien.setFocusable(false);
    tabNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
    tabNhanVien.setIconTextGap(25);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 39;
    gridBagConstraints.ipady = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
    gridBagConstraints.weightx = 0.1;
    pannelLeft.add(tabNhanVien, gridBagConstraints);

    tabKhachHang.setBackground(Color.white);
    tabKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    tabKhachHang.setForeground(new java.awt.Color(15, 102, 165));
    tabKhachHang.setIcon(utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/icon/ico-khachhang.png"))  
    , sizeIconBar, sizeIconBar));
    tabKhachHang.setText("Khách hàng");
    tabKhachHang.setFocusable(false);
    tabKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
    tabKhachHang.setIconTextGap(25);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 39;
    gridBagConstraints.ipady = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
    gridBagConstraints.weightx = 0.1;
    pannelLeft.add(tabKhachHang, gridBagConstraints);

    btnDangXuat.setBackground(Color.white);
    btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btnDangXuat.setForeground(new java.awt.Color(15, 102, 165));
    btnDangXuat.setIcon(utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/icon/btn-logout.png"))
    , sizeIconBar, sizeIconBar));
    btnDangXuat.setText("Đăng xuất");
    btnDangXuat.setFocusable(false);
    btnDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
    btnDangXuat.setIconTextGap(25);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 18;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 39;
    gridBagConstraints.ipady = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
    gridBagConstraints.weightx = 0.4;
    pannelLeft.add(btnDangXuat, gridBagConstraints);

    tabNhaCungCap1.setBackground(Color.white);
    tabNhaCungCap1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    tabNhaCungCap1.setForeground(new java.awt.Color(15, 102, 165));
    tabNhaCungCap1.setIcon(utilities.ImageProcessing.resizeIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/icon/ico-nhacungcap.png"))  
    , sizeIconBar, sizeIconBar));
    tabNhaCungCap1.setText("Nhà cung cấp");
    tabNhaCungCap1.setFocusable(false);
    tabNhaCungCap1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
    tabNhaCungCap1.setIconTextGap(25);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 12;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 39;
    gridBagConstraints.ipady = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
    gridBagConstraints.weightx = 0.1;
    pannelLeft.add(tabNhaCungCap1, gridBagConstraints);

    jPannelSplit.setLeftComponent(pannelLeft);

    jPanel6.add(jPannelSplit, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUserActionPerformed

    private void tabBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabBanHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabBanHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JComboBox<String> cboUser;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jPannelSplit;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel pannelLeft;
    private javax.swing.JButton tabBanHang;
    private javax.swing.JButton tabKhachHang;
    private javax.swing.JButton tabKhuyenMai;
    private javax.swing.JButton tabNhaCungCap1;
    private javax.swing.JButton tabNhanVien;
    private javax.swing.JButton tabSanPham;
    private javax.swing.JButton tabThongKe;
    // End of variables declaration//GEN-END:variables
}
