/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author NguyenThanhLuan
 */
public class TAB_KhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form TAB_KhuyenMai
     */
    public TAB_KhuyenMai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlALL = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NhapMa = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        hinhThuc = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btnKhuyenMaiTao = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        titleSelectKhuyenMai = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tableSelectKhuyenMai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlALL.setLayout(new java.awt.BorderLayout());

        title.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 145, 239));
        jLabel1.setText("Quản lý khuyến mãi");
        title.add(jLabel1);
        title.add(filler1);

        pnlALL.add(title, java.awt.BorderLayout.NORTH);

        center.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        center.setLayout(new javax.swing.BoxLayout(center, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 145, 239)), "Tạo khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        NhapMa.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Mã khuyến mãi:");
        jLabel2.setPreferredSize(new java.awt.Dimension(140, 16));
        jPanel10.add(jLabel2);
        jPanel10.add(jTextField5);

        NhapMa.add(jPanel10);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Tên khuyến mãi:");
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 16));
        jPanel9.add(jLabel3);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField6);

        NhapMa.add(jPanel9);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Số lượng áp dụng tối đã:");
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 16));
        jPanel8.add(jLabel4);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField7);

        NhapMa.add(jPanel8);

        jPanel3.add(NhapMa);

        hinhThuc.setPreferredSize(new java.awt.Dimension(425, 80));
        hinhThuc.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel15.setLayout(new java.awt.GridLayout(4, 1));

        jLabel5.setText("Hình thức giảm giá");
        jPanel15.add(jLabel5);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel15.add(jComboBox2);

        jLabel7.setText("Thời gian bắt đầu giảm giá");
        jPanel15.add(jLabel7);
        jPanel15.add(jDateChooser1);

        hinhThuc.add(jPanel15);

        jPanel7.setLayout(new java.awt.GridLayout(4, 1));

        jLabel6.setText("Mức giảm giá");
        jPanel7.add(jLabel6);
        jPanel7.add(jTextField2);

        jLabel8.setText("Thời gian kết thúc giảm giá");
        jPanel7.add(jLabel8);
        jPanel7.add(jDateChooser2);

        hinhThuc.add(jPanel7);

        jPanel3.add(hinhThuc);

        btnKhuyenMaiTao.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 10, 1));
        btnKhuyenMaiTao.setPreferredSize(new java.awt.Dimension(0, 30));
        btnKhuyenMaiTao.setLayout(new java.awt.GridLayout(1, 0, 18, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(15, 145, 239));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jPanel5.add(jButton1);

        btnKhuyenMaiTao.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setBackground(new java.awt.Color(239, 162, 162));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hủy bỏ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        btnKhuyenMaiTao.add(jPanel6);

        jPanel3.add(btnKhuyenMaiTao);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 1, 1));
        jPanel4.setLayout(new java.awt.BorderLayout());

        titleSelectKhuyenMai.setPreferredSize(new java.awt.Dimension(602, 72));
        titleSelectKhuyenMai.setLayout(new java.awt.GridLayout(2, 2, 0, 8));

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setText("Áp dụng theo: ");
        jPanel17.add(jLabel10);
        jPanel17.add(filler3);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel17.add(jComboBox3);

        titleSelectKhuyenMai.add(jPanel17);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        titleSelectKhuyenMai.add(jPanel16);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jCheckBox1.setText("Áp dụng cho tất cả");
        jPanel14.add(jCheckBox1);

        titleSelectKhuyenMai.add(jPanel14);

        jPanel12.setLayout(new java.awt.BorderLayout(10, 0));

        jTextField1.setText("Mã sản phẩm, tên sản phẩm,...");
        jPanel12.add(jTextField1, java.awt.BorderLayout.CENTER);

        jButton3.setText("jButton3");
        jPanel12.add(jButton3, java.awt.BorderLayout.EAST);

        titleSelectKhuyenMai.add(jPanel12);

        jPanel4.add(titleSelectKhuyenMai, java.awt.BorderLayout.PAGE_START);

        tableSelectKhuyenMai.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        tableSelectKhuyenMai.setPreferredSize(new java.awt.Dimension(870, 200));
        tableSelectKhuyenMai.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chọn", "Mã sản phẩm", "Tên sản phẩm"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tableSelectKhuyenMai.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(tableSelectKhuyenMai, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        center.add(jPanel1);
        center.add(filler2);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 145, 239)), "Danh sách khuyến mãi"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1754, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        center.add(jPanel2);

        pnlALL.add(center, java.awt.BorderLayout.CENTER);

        add(pnlALL, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NhapMa;
    private javax.swing.JPanel btnKhuyenMaiTao;
    private javax.swing.JPanel center;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel hinhThuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel pnlALL;
    private javax.swing.JPanel tableSelectKhuyenMai;
    private javax.swing.JPanel title;
    private javax.swing.JPanel titleSelectKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
