/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import bus.KhuyenMai_BUS;
import entities.KhuyenMai;
import entities.NhaCungCap;

/**
 *
 * @author NguyenThanhLuan
 */
public class TAB_KhuyenMai extends javax.swing.JPanel {
	private DefaultTableModel tableModel;
	private KhuyenMai_BUS khuyenMai_BUS;
	private ArrayList<KhuyenMai> danhSachKM;
    /**
     * Creates new form TAB_KhuyenMai
     */
    public TAB_KhuyenMai() {
        initComponents();
        khuyenMai_BUS = new KhuyenMai_BUS();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlALL = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NhapMa = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenKM = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        soLuongApDung = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDonHangTu = new javax.swing.JTextField();
        hinhThuc = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtHinhThuc = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNgayBatDau = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMucGiamGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgayKetThuc = new com.toedter.calendar.JDateChooser();
        btnKhuyenMaiTao = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        titleSelectKhuyenMai = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        comboboxApDung = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        checkBoxSelectChoTatCa = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        TimMaSanPham = new javax.swing.JTextField();
        btnTIMKiem = new javax.swing.JButton();
        tableSelectKhuyenMai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChonSP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        txtTimKMTheoMa = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        jLabel11 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        txtTimTheoMucGiam = new javax.swing.JComboBox<>();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        jLabel12 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        txtTimTheoHinhThuc = new javax.swing.JComboBox<>();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        txtTimKiemKhuyenMai = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKM = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnlALL.setLayout(new java.awt.BorderLayout());

        title.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 145, 239));
        jLabel1.setText("Quản lý khuyến mãi");
        title.add(jLabel1);
        title.add(filler1);

        pnlALL.add(title, java.awt.BorderLayout.NORTH);

        center.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        center.setLayout(new javax.swing.BoxLayout(center, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 145, 239)), "Tạo khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1224, 350));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel3.setPreferredSize(new java.awt.Dimension(441, 300));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        NhapMa.setPreferredSize(new java.awt.Dimension(204, 120));
        NhapMa.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Mã khuyến mãi:");
        jLabel2.setPreferredSize(new java.awt.Dimension(140, 16));
        jPanel10.add(jLabel2);
        jPanel10.add(txtMaKM);

        NhapMa.add(jPanel10);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Tên khuyến mãi:");
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 16));
        jPanel9.add(jLabel3);
        jPanel9.add(txtTenKM);

        NhapMa.add(jPanel9);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Số lượng áp dụng tối đã:");
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 16));
        jPanel13.add(jLabel4);
        jPanel13.add(soLuongApDung);

        jPanel8.add(jPanel13);

        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setText("Đơn hàng từ: ");
        jPanel18.add(jLabel9);
        jPanel18.add(txtDonHangTu);

        jPanel8.add(jPanel18);

        NhapMa.add(jPanel8);

        jPanel3.add(NhapMa);

        hinhThuc.setPreferredSize(new java.awt.Dimension(425, 120));
        hinhThuc.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel15.setLayout(new java.awt.GridLayout(4, 1));

        jLabel5.setText("Hình thức giảm giá");
        jPanel15.add(jLabel5);

        txtHinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phần trăm ", "Giá trị" }));
        jPanel15.add(txtHinhThuc);

        jLabel7.setText("Thời gian bắt đầu giảm giá");
        jPanel15.add(jLabel7);
        jPanel15.add(txtNgayBatDau);

        hinhThuc.add(jPanel15);

        jPanel7.setLayout(new java.awt.GridLayout(4, 1));

        jLabel6.setText("Mức giảm giá");
        jPanel7.add(jLabel6);
        jPanel7.add(txtMucGiamGia);

        jLabel8.setText("Thời gian kết thúc giảm giá");
        jPanel7.add(jLabel8);
        jPanel7.add(txtNgayKetThuc);

        hinhThuc.add(jPanel7);

        jPanel3.add(hinhThuc);

        btnKhuyenMaiTao.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 10, 1));
        btnKhuyenMaiTao.setPreferredSize(new java.awt.Dimension(0, 80));
        btnKhuyenMaiTao.setLayout(new java.awt.GridLayout(1, 0, 18, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btnLuu.setBackground(new java.awt.Color(15, 145, 239));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/icon-luuKM.png"))); // NOI18N
        btnLuu.setText("Thêm");
        jPanel5.add(btnLuu);

        btnKhuyenMaiTao.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btnHuy.setBackground(new java.awt.Color(239, 162, 162));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/icon-huyKM.png"))); // NOI18N
        btnHuy.setText("Hủy bỏ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel6.add(btnHuy);

        btnKhuyenMaiTao.add(jPanel6);

        jPanel3.add(btnKhuyenMaiTao);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 1, 1));
        jPanel4.setPreferredSize(new java.awt.Dimension(602, 310));
        jPanel4.setLayout(new java.awt.BorderLayout());

        titleSelectKhuyenMai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        titleSelectKhuyenMai.setPreferredSize(new java.awt.Dimension(602, 72));
        titleSelectKhuyenMai.setLayout(new java.awt.GridLayout(2, 2, 0, 8));

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setText("Áp dụng theo: ");
        jPanel17.add(jLabel10);
        jPanel17.add(filler3);

        comboboxApDung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel17.add(comboboxApDung);

        titleSelectKhuyenMai.add(jPanel17);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        titleSelectKhuyenMai.add(jPanel16);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        checkBoxSelectChoTatCa.setText("Áp dụng cho tất cả");
        jPanel14.add(checkBoxSelectChoTatCa);

        titleSelectKhuyenMai.add(jPanel14);

        jPanel12.setLayout(new java.awt.BorderLayout(10, 0));

        TimMaSanPham.setText("Mã sản phẩm, tên sản phẩm,...");
        jPanel12.add(TimMaSanPham, java.awt.BorderLayout.CENTER);

        btnTIMKiem.setBackground(new java.awt.Color(15, 145, 239));
        btnTIMKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/icon-addKM.png"))); // NOI18N
        btnTIMKiem.setPreferredSize(new java.awt.Dimension(80, 23));
        btnTIMKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTIMKiemActionPerformed(evt);
            }
        });
        jPanel12.add(btnTIMKiem, java.awt.BorderLayout.EAST);

        titleSelectKhuyenMai.add(jPanel12);

        jPanel4.add(titleSelectKhuyenMai, java.awt.BorderLayout.PAGE_START);

        tableSelectKhuyenMai.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        tableSelectKhuyenMai.setPreferredSize(new java.awt.Dimension(870, 200));
        tableSelectKhuyenMai.setLayout(new java.awt.BorderLayout());

        tableChonSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chọn", "Mã sản phẩm", "Tên sản phẩm"
            }
        ));
        jScrollPane1.setViewportView(tableChonSP);

        tableSelectKhuyenMai.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(tableSelectKhuyenMai, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        center.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 145, 239)), "Danh sách khuyến mãi"));
        jPanel2.setPreferredSize(new java.awt.Dimension(1764, 170));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel19.setMinimumSize(new java.awt.Dimension(163, 50));
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel20.setMinimumSize(new java.awt.Dimension(153, 28));
        jPanel20.setPreferredSize(new java.awt.Dimension(660, 28));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        txtTimKMTheoMa.setPreferredSize(new java.awt.Dimension(180, 22));
        jPanel20.add(txtTimKMTheoMa);
        jPanel20.add(filler6);

        jLabel11.setText("Mức giảm");
        jPanel20.add(jLabel11);
        jPanel20.add(filler4);

        txtTimTheoMucGiam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Tăng dần", "Giảm dần" }));
        txtTimTheoMucGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimTheoMucGiamActionPerformed(evt);
            }
        });
        jPanel20.add(txtTimTheoMucGiam);
        jPanel20.add(filler7);

        jLabel12.setText("Hình thức");
        jPanel20.add(jLabel12);
        jPanel20.add(filler5);

        txtTimTheoHinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả ", "Giá trị ", "Phần trăm" }));
        jPanel20.add(txtTimTheoHinhThuc);
        jPanel20.add(filler8);
        jPanel20.add(filler2);

        txtTimKiemKhuyenMai.setBackground(new java.awt.Color(15, 145, 239));
        txtTimKiemKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/icon-search.png"))); // NOI18N
        txtTimKiemKhuyenMai.setMinimumSize(new java.awt.Dimension(26, 32));
        txtTimKiemKhuyenMai.setPreferredSize(new java.awt.Dimension(79, 32));
        jPanel20.add(txtTimKiemKhuyenMai);

        jPanel19.add(jPanel20);

        jPanel2.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        tableKM.setModel(tableModel = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khuyễn mãi", "Tên khuyến mãi", "Loại khuyến mãi", "Giá trị", "Áp dụng từ đơn", "Ngày bắt đầu", "Ngày kết thúc", "Xem sản phẩm"
            }
        ));
        tableKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableKM);

        jPanel11.add(jScrollPane3);

        jPanel2.add(jPanel11, java.awt.BorderLayout.CENTER);

        center.add(jPanel2);

        pnlALL.add(center, java.awt.BorderLayout.CENTER);

        add(pnlALL, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnTIMKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTIMKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTIMKiemActionPerformed

    private void txtTimTheoMucGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimTheoMucGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimTheoMucGiamActionPerformed

    private void tableKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableKMMouseClicked

    private void loadData() {
    	tableKM.removeAll();
    	tableKM.setRowSelectionAllowed(false);
    	tableModel.setRowCount(0);
    	danhSachKM = new ArrayList<>();
    	danhSachKM = khuyenMai_BUS.getAllKhuyenMai();
    	
    	int stt = 1;
    	for(KhuyenMai km : danhSachKM) {
    		tableModel.addRow(new Object[] {stt++, km.getCodeKhuyenMai(), km.getTenKhuyenMai(), km.getLoaiKhuyenMai(), km.getNgayKhuyenMai(), km.getNgayHetHanKM(),km.getDonHangTu(), km.getSoLuongKhuyenMai(), km.getSoLuotDaApDung()});
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NhapMa;
    private javax.swing.JTextField TimMaSanPham;
    private javax.swing.JButton btnHuy;
    private javax.swing.JPanel btnKhuyenMaiTao;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTIMKiem;
    private javax.swing.JPanel center;
    private javax.swing.JCheckBox checkBoxSelectChoTatCa;
    private javax.swing.JComboBox<String> comboboxApDung;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JPanel hinhThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlALL;
    private javax.swing.JTextField soLuongApDung;
    private javax.swing.JTable tableChonSP;
    private javax.swing.JTable tableKM;
    private javax.swing.JPanel tableSelectKhuyenMai;
    private javax.swing.JPanel title;
    private javax.swing.JPanel titleSelectKhuyenMai;
    private javax.swing.JTextField txtDonHangTu;
    private javax.swing.JComboBox<String> txtHinhThuc;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtMucGiamGia;
    private com.toedter.calendar.JDateChooser txtNgayBatDau;
    private com.toedter.calendar.JDateChooser txtNgayKetThuc;
    private javax.swing.JTextField txtTenKM;
    private javax.swing.JTextField txtTimKMTheoMa;
    private javax.swing.JButton txtTimKiemKhuyenMai;
    private javax.swing.JComboBox<String> txtTimTheoHinhThuc;
    private javax.swing.JComboBox<String> txtTimTheoMucGiam;
    // End of variables declaration//GEN-END:variables
}
