
package gui;

import bus.ChiTietHoaDon_BUS;
import bus.HoaDon_BUS;
import bus.SanPham_BUS;
import connectDB.ConnectDB;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;

import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

import entities.HoaDon;
import entities.SanPham;
import utilities.*;

/**
 *
 * @author duong
 */
public class TAB_BanHang extends javax.swing.JPanel implements MouseListener {
    private SanPham_BUS sanPham_BUS;
    private HoaDon_BUS hoaDon_BUS;
    private ChiTietHoaDon_BUS chiTietHoaDon_BUS;
    /**
     * Creates new form TAB_BanHang
     */
    public TAB_BanHang() {
    	// Hoá đơn mặc định.
    	HoaDon hoaDon = new HoaDon();
        sanPham_BUS = new SanPham_BUS();
    	
        initComponents();
        
        jTable1.getColumn("-").setCellRenderer(new ButtonRender(
                ImageProcessing.resizeIcon(
                    new ImageIcon(getClass().getResource("/img/icon/btn-decrease.png"))
                , 15, 15)
        ));

        jTable1.getColumn("+").setCellRenderer(new ButtonRender(
                ImageProcessing.resizeIcon(
                    new ImageIcon(getClass().getResource("/img/icon/btn-increase.png"))
                , 15, 15)
        ));
        jTable1.getColumn("Xoá").setCellRenderer(new ButtonRender(
                ImageProcessing.resizeIcon(
                    new ImageIcon(getClass().getResource("/img/icon/btn-delete-no-transparent.png"))
                , 12, 15)
        ));
        
        jTable1.addMouseListener(this);
        
        // Placeholder text
        ((utilities.JTextFieldPlaceHolder) txtMaKhachHang).setPlaceholder("Nhập mã KH hoặc SĐT");
        ((utilities.JTextFieldPlaceHolder) txtKhuyenMai).setPlaceholder("Nhập mã khuyến mãi");
        WindowTitle.setTitle("Quản lý bán hàng");
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
    	// TODO Auto-generated method stub
    	if (e.getSource().equals(jTable1)) {
    		JTable tbl = (JTable)e.getSource();
            int row = tbl.rowAtPoint( e.getPoint() );
            int column = tbl.columnAtPoint( e.getPoint() );
            
            switch (column) {
		case 4 -> {
                    if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(null, "Giảm số lượng" + tbl.getValueAt(row, 1) + " khỏi hoá đơn không??", "Xác nhận thao tác", JOptionPane.CANCEL_OPTION)){
						
                    }
		}
                case 6 -> {
                    if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(null, "Tăng số lượng" + tbl.getValueAt(row, 1) + " khỏi hoá đơn không??", "Xác nhận thao tác", JOptionPane.CANCEL_OPTION)){
						
                    }
		}
		case 9 -> {
                    if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá sản phẩm " + tbl.getValueAt(row, 1) + " khỏi hoá đơn không??", "Xác nhận thao tác", JOptionPane.CANCEL_OPTION)){
						
                    }
		}
		default ->{
		}
            }
            
    	}
    	
    	
    }
    
    @Override
    public void mouseEntered(MouseEvent e) {
    	// TODO Auto-generated method stub
    	
    }
    
    @Override
    public void mouseExited(MouseEvent e) {
    	// TODO Auto-generated method stub
    	
    }
    
    @Override
    public void mousePressed(MouseEvent e) {
    	// TODO Auto-generated method stub
    	
    }
    
    @Override
    public void mouseReleased(MouseEvent e) {
    	// TODO Auto-generated method stub
    	
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        TAB_BanHang_HoaDon = new javax.swing.JPanel();
        TAB_BanHang_DanhSachHoaDon = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout TAB_BanHang_HoaDonLayout = new javax.swing.GroupLayout(TAB_BanHang_HoaDon);
        TAB_BanHang_HoaDon.setLayout(TAB_BanHang_HoaDonLayout);
        TAB_BanHang_HoaDonLayout.setHorizontalGroup(
            TAB_BanHang_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        TAB_BanHang_HoaDonLayout.setVerticalGroup(
            TAB_BanHang_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hoá đơn", TAB_BanHang_HoaDon);

        javax.swing.GroupLayout TAB_BanHang_DanhSachHoaDonLayout = new javax.swing.GroupLayout(TAB_BanHang_DanhSachHoaDon);
        TAB_BanHang_DanhSachHoaDon.setLayout(TAB_BanHang_DanhSachHoaDonLayout);
        TAB_BanHang_DanhSachHoaDonLayout.setHorizontalGroup(
            TAB_BanHang_DanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        TAB_BanHang_DanhSachHoaDonLayout.setVerticalGroup(
            TAB_BanHang_DanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Danh sách hoá đơn", TAB_BanHang_DanhSachHoaDon);

    add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSanPhamActionPerformed

    private void txtMaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKhachHangActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void txtKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhuyenMaiActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAddSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSanPhamActionPerformed
        // TODO add your handling code here:
        
        String maSanPham = txtMaSanPham.getText().trim();
        if (maSanPham.isEmpty() || maSanPham.isBlank()){
            ErrorMessage.showMessageWithFocusTextField("Thông tin", "Để thêm sản phẩm vào hoá đơn, hãy thêm mã sản phẩm trước", txtMaSanPham);
            return;
        }
        
        if (maSanPham.matches("\\D")){
            ErrorMessage.showMessageWithFocusTextField("Thông tin", "Barcode/Mã sản phẩm nội bộ không hợp lệ!", txtMaSanPham);
            return;
        }
        

        SanPham x = sanPham_BUS.getChiMotSanPhamTheoMaHoacBarcode(maSanPham);
        
        if (x == null){
            ErrorMessage.showMessageWithFocusTextField("Thông tin", "Sản phẩm không tồn tại, vui lòng kiểm tra lại barcode", txtMaSanPham);
            return;
        }
            
        
        
    }//GEN-LAST:event_btnAddSanPhamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel tabBanHang_HoaDon_Center;
    private javax.swing.JPanel tabBanHang_HoaDon_Right;
    private javax.swing.JPanel tabBanHang_HoaDon_Right_GiamGia;
    private javax.swing.JPanel tabBanHang_HoaDon_Right_GiamGia1;
    private javax.swing.JPanel tabBanHang_HoaDon_Right_KhachHang;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaSanPham;
    // End of variables declaration//GEN-END:variables
}
